TARGET_RES = (256, 256)
SEQ_LEN = 5
BASE_CHANNELS = 64
NUM_LAYERS = 3

# Training hyperparameters
BATCH_SIZE = 1
LEARNING_RATE = 0.001

# Mask hyperparameters
MASK_PIXEL_MOVEMENT_SPEED = 5
MASK_SIZE_RANGE = (50, 100)